theme = "archie"
baseURL = 'https://pid1.dev/'
languageCode = 'en-us'
title = 'pid1'

[module.hugoVersion]
min = "0.113.0"

[[menu.main]]
identifier = "post"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "rss"
name = "RSS"
url = "/posts/feed.xml"
weight = 3

[taxonomies]
tags = "tags"

[markup.asciidocExt]
backend = 'html5'
extensions = []
failureLevel = 'fatal'
noHeaderOrFooter = true
preserveTOC = false
safeMode = 'unsafe'
sectionNumbers = false
trace = false
verbose = false
workingFolderCurrent = false

[markup.asciidocExt.attributes]
source-highlighter = 'highlight.js'

[security.exec]
allow = ['^asciidoctor$']

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"